# This is a basic workflow to help you get started with Actions

name: Deven Sharma Final Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: ${{secrets.589b3420-6170-43af-86c8-87a3111c15b9}}
        MESSAGE: "Hey Deven Sharma, There's a new build!"
    


 
